---
- name: Pull docker image of Calculator
  hosts: localhost
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull yamangoyal209/calculator_image

    - name: running container
      shell: docker create -it --name calculator yamangoyal209/calculator_image /bin/bash